<?php

namespace ContainerRL9vqtO;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSchebTwoFactor_Security_Totp_Validator_UserTotpCodeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'scheb_two_factor.security.totp.validator.user_totp_code' shared service.
     *
     * @return \Scheb\TwoFactorBundle\Security\TwoFactor\Validator\Constraints\UserTotpCodeValidator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'validator'.\DIRECTORY_SEPARATOR.'ConstraintValidatorInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'validator'.\DIRECTORY_SEPARATOR.'ConstraintValidator.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'scheb'.\DIRECTORY_SEPARATOR.'2fa-totp'.\DIRECTORY_SEPARATOR.'Security'.\DIRECTORY_SEPARATOR.'TwoFactor'.\DIRECTORY_SEPARATOR.'Validator'.\DIRECTORY_SEPARATOR.'Constraints'.\DIRECTORY_SEPARATOR.'UserTotpCodeValidator.php';

        $a = ($container->services['scheb_two_factor.security.totp_authenticator'] ?? $container->load('getSchebTwoFactor_Security_TotpAuthenticatorService'));

        if (isset($container->privates['scheb_two_factor.security.totp.validator.user_totp_code'])) {
            return $container->privates['scheb_two_factor.security.totp.validator.user_totp_code'];
        }

        $instance = new \Scheb\TwoFactorBundle\Security\TwoFactor\Validator\Constraints\UserTotpCodeValidator(($container->privates['security.token_storage'] ?? self::getSecurity_TokenStorageService($container)), $a);

        if (isset($container->privates['scheb_two_factor.security.totp.validator.user_totp_code'])) {
            return $container->privates['scheb_two_factor.security.totp.validator.user_totp_code'];
        }

        return $container->privates['scheb_two_factor.security.totp.validator.user_totp_code'] = $instance;
    }
}
