<?php

namespace ContainerRL9vqtO;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTestMailerCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\TestMailerCommand' shared autowired service.
     *
     * @return \App\Command\TestMailerCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'Command.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'TestMailerCommand.php';

        $container->privates['App\\Command\\TestMailerCommand'] = $instance = new \App\Command\TestMailerCommand(($container->privates['mailer.mailer'] ?? $container->load('getMailer_MailerService')), $container->getEnv('default::MAILER_FROM'));

        $instance->setName('app:mailer:test');
        $instance->setDescription('Send a test email to verify Gmail SMTP configuration');

        return $instance;
    }
}
