<?php

namespace ContainerRL9vqtO;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTicketQrCodeGeneratorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\TicketQrCodeGenerator' shared autowired service.
     *
     * @return \App\Service\TicketQrCodeGenerator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'TicketQrCodeGenerator.php';

        return $container->privates['App\\Service\\TicketQrCodeGenerator'] = new \App\Service\TicketQrCodeGenerator(($container->services['router'] ?? self::getRouterService($container)), \dirname(__DIR__, 4));
    }
}
