<?php

namespace Container5CteMxn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_7jSP4cPService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.7jSP4cP' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.7jSP4cP'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'event' => ['privates', '.errored..service_locator.7jSP4cP.App\\Entity\\Event', NULL, 'Cannot autowire service ".service_locator.7jSP4cP": it needs an instance of "App\\Entity\\Event" but this type has been excluded because it\'s a Doctrine entity.'],
        ], [
            'event' => 'App\\Entity\\Event',
        ]);
    }
}
