<?php

namespace Container5CteMxn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDashboardControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator._9ZBp5y.App\Controller\Admin\DashboardController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator._9ZBp5y.App\\Controller\\Admin\\DashboardController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
            'eventRepository' => ['privates', 'App\\Repository\\EventRepository', 'getEventRepositoryService', true],
            'orderRepository' => ['privates', 'App\\Repository\\OrderRepository', 'getOrderRepositoryService', true],
            'serviceProviderRepository' => ['privates', 'App\\Repository\\ServiceProviderRepository', 'getServiceProviderRepositoryService', true],
            'organizerRepository' => ['privates', 'App\\Repository\\OrganizerRepository', 'getOrganizerRepositoryService', true],
        ], [
            'userRepository' => 'App\\Repository\\UserRepository',
            'eventRepository' => 'App\\Repository\\EventRepository',
            'orderRepository' => 'App\\Repository\\OrderRepository',
            'serviceProviderRepository' => 'App\\Repository\\ServiceProviderRepository',
            'organizerRepository' => 'App\\Repository\\OrganizerRepository',
        ]))->withContext('App\\Controller\\Admin\\DashboardController::index()', $container);
    }
}
