<?php

namespace Container5CteMxn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMailerDsnEnvVarProcessorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\DependencyInjection\MailerDsnEnvVarProcessor' shared autowired service.
     *
     * @return \App\DependencyInjection\MailerDsnEnvVarProcessor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'dependency-injection'.\DIRECTORY_SEPARATOR.'EnvVarProcessorInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'DependencyInjection'.\DIRECTORY_SEPARATOR.'MailerDsnEnvVarProcessor.php';

        return $container->privates['App\\DependencyInjection\\MailerDsnEnvVarProcessor'] = new \App\DependencyInjection\MailerDsnEnvVarProcessor();
    }
}
