<?php

namespace Container5CteMxn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProfileControllerchangePasswordService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.hLEvwD7.App\Controller\ProfileController::changePassword()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'passwordHasher' => ['privates', 'security.user_password_hasher', 'getSecurity_UserPasswordHasherService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'passwordHasher' => '?',
            'entityManager' => '?',
        ]))->withContext('App\\Controller\\ProfileController::changePassword()', $container);

        if (isset($container->privates['.service_locator.hLEvwD7.App\\Controller\\ProfileController::changePassword()'])) {
            return $container->privates['.service_locator.hLEvwD7.App\\Controller\\ProfileController::changePassword()'];
        }

        return $container->privates['.service_locator.hLEvwD7.App\\Controller\\ProfileController::changePassword()'] = $instance;
    }
}
