<?php

namespace Container5CteMxn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReclamation2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.90BlalF.App\Entity\Reclamation' shared service.
     *
     * @return \App\Entity\Reclamation
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.90BlalF": it needs an instance of "App\\Entity\\Reclamation" but this type has been excluded because it\'s a Doctrine entity.');
    }
}
