<?php

namespace Container5CteMxn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReclamationControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.90BlalF.App\Controller\ReclamationController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.90BlalF'] ?? $container->load('get_ServiceLocator_90BlalFService'));

        if (isset($container->privates['.service_locator.90BlalF.App\\Controller\\ReclamationController::edit()'])) {
            return $container->privates['.service_locator.90BlalF.App\\Controller\\ReclamationController::edit()'];
        }

        $instance = $a->withContext('App\\Controller\\ReclamationController::edit()', $container);

        if (isset($container->privates['.service_locator.90BlalF.App\\Controller\\ReclamationController::edit()'])) {
            return $container->privates['.service_locator.90BlalF.App\\Controller\\ReclamationController::edit()'];
        }

        return $container->privates['.service_locator.90BlalF.App\\Controller\\ReclamationController::edit()'] = $instance;
    }
}
