<?php

namespace Container5CteMxn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReponseService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.9iNU3ga.App\Entity\Reponse' shared service.
     *
     * @return \App\Entity\Reponse
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.9iNU3ga": it needs an instance of "App\\Entity\\Reponse" but this type has been excluded because it\'s a Doctrine entity.');
    }
}
