<?php

namespace ContainerRSaQVVX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_H_H0zHfService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.H.h0zHf' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'nlpService' => ['privates', 'App\\Service\\RfqNlpMatchingService', 'getRfqNlpMatchingServiceService', true],
        ], [
            'nlpService' => 'App\\Service\\RfqNlpMatchingService',
        ]);

        if (isset($container->privates['.service_locator.H.h0zHf'])) {
            return $container->privates['.service_locator.H.h0zHf'];
        }

        return $container->privates['.service_locator.H.h0zHf'] = $instance;
    }
}
