<?php

namespace ContainerRSaQVVX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Messenger_HandlerDescriptor_CRvZLYvService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.messenger.handler_descriptor.CRvZLYv' shared service.
     *
     * @return \Symfony\Component\Messenger\Handler\HandlerDescriptor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'messenger'.\DIRECTORY_SEPARATOR.'Handler'.\DIRECTORY_SEPARATOR.'HandlerDescriptor.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'MessageHandler'.\DIRECTORY_SEPARATOR.'AnalyzeProposalHandler.php';

        $a = ($container->privates['App\\Service\\RfqNlpMatchingService'] ?? $container->load('getRfqNlpMatchingServiceService'));

        if (isset($container->privates['.messenger.handler_descriptor.CRvZLYv'])) {
            return $container->privates['.messenger.handler_descriptor.CRvZLYv'];
        }

        $instance = new \Symfony\Component\Messenger\Handler\HandlerDescriptor(new \App\MessageHandler\AnalyzeProposalHandler(($container->privates['App\\Repository\\ServiceProposalRepository'] ?? $container->load('getServiceProposalRepositoryService')), $a), []);

        if (isset($container->privates['.messenger.handler_descriptor.CRvZLYv'])) {
            return $container->privates['.messenger.handler_descriptor.CRvZLYv'];
        }

        return $container->privates['.messenger.handler_descriptor.CRvZLYv'] = $instance;
    }
}
