<?php

namespace ContainerRSaQVVX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_1ITx0wWService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.1ITx0wW' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.1ITx0wW'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'provider' => ['privates', '.errored..service_locator.1ITx0wW.App\\Entity\\ServiceProvider', NULL, 'Cannot autowire service ".service_locator.1ITx0wW": it needs an instance of "App\\Entity\\ServiceProvider" but this type has been excluded because it\'s a Doctrine entity.'],
        ], [
            'provider' => 'App\\Entity\\ServiceProvider',
        ]);
    }
}
