<?php

namespace ContainerRSaQVVX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProviderScoringServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\ProviderScoringService' shared autowired service.
     *
     * @return \App\Service\ProviderScoringService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'ProviderScoringService.php';

        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        if (isset($container->privates['App\\Service\\ProviderScoringService'])) {
            return $container->privates['App\\Service\\ProviderScoringService'];
        }

        $instance = new \App\Service\ProviderScoringService(($container->privates['App\\Repository\\ServiceBookingRepository'] ?? $container->load('getServiceBookingRepositoryService')), ($container->privates['App\\Repository\\ServiceProposalRepository'] ?? $container->load('getServiceProposalRepositoryService')), $a);

        if (isset($container->privates['App\\Service\\ProviderScoringService'])) {
            return $container->privates['App\\Service\\ProviderScoringService'];
        }

        return $container->privates['App\\Service\\ProviderScoringService'] = $instance;
    }
}
