<?php

namespace ContainerRSaQVVX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRfqMailerServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\RfqMailerService' shared autowired service.
     *
     * @return \App\Service\RfqMailerService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'RfqMailerService.php';

        $a = ($container->privates['mailer.mailer'] ?? $container->load('getMailer_MailerService'));

        if (isset($container->privates['App\\Service\\RfqMailerService'])) {
            return $container->privates['App\\Service\\RfqMailerService'];
        }

        $instance = new \App\Service\RfqMailerService($a, ($container->privates['App\\Repository\\ServiceProviderRepository'] ?? $container->load('getServiceProviderRepositoryService')));

        if (isset($container->privates['App\\Service\\RfqMailerService'])) {
            return $container->privates['App\\Service\\RfqMailerService'];
        }

        return $container->privates['App\\Service\\RfqMailerService'] = $instance;
    }
}
