<?php

namespace ContainerRSaQVVX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRfqNlpMatchingServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\RfqNlpMatchingService' shared autowired service.
     *
     * @return \App\Service\RfqNlpMatchingService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'RfqNlpMatchingService.php';

        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        if (isset($container->privates['App\\Service\\RfqNlpMatchingService'])) {
            return $container->privates['App\\Service\\RfqNlpMatchingService'];
        }

        $instance = new \App\Service\RfqNlpMatchingService(($container->privates['http_client.uri_template'] ?? self::getHttpClient_UriTemplateService($container)), $a, $container->getEnv('OPENROUTER_API_KEY'), ($container->privates['monolog.logger'] ?? self::getMonolog_LoggerService($container)));

        if (isset($container->privates['App\\Service\\RfqNlpMatchingService'])) {
            return $container->privates['App\\Service\\RfqNlpMatchingService'];
        }

        return $container->privates['App\\Service\\RfqNlpMatchingService'] = $instance;
    }
}
