<?php

namespace ContainerRSaQVVX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReponseControllernewService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator._tQWeWb.App\Controller\ReponseController::new()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'reclamationRepository' => ['privates', 'App\\Repository\\ReclamationRepository', 'getReclamationRepositoryService', true],
        ], [
            'entityManager' => '?',
            'reclamationRepository' => 'App\\Repository\\ReclamationRepository',
        ]))->withContext('App\\Controller\\ReponseController::new()', $container);

        if (isset($container->privates['.service_locator._tQWeWb.App\\Controller\\ReponseController::new()'])) {
            return $container->privates['.service_locator._tQWeWb.App\\Controller\\ReponseController::new()'];
        }

        return $container->privates['.service_locator._tQWeWb.App\\Controller\\ReponseController::new()'] = $instance;
    }
}
