<?php

namespace ContainerRSaQVVX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReclamationControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.35tn9Xj.App\Controller\ReclamationController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.35tn9Xj.App\\Controller\\ReclamationController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'reclamation' => ['privates', '.errored..service_locator.35tn9Xj.App\\Entity\\Reclamation', NULL, 'Cannot autowire service ".service_locator.35tn9Xj": it needs an instance of "App\\Entity\\Reclamation" but this type has been excluded because it\'s a Doctrine entity.'],
        ], [
            'reclamation' => 'App\\Entity\\Reclamation',
        ]))->withContext('App\\Controller\\ReclamationController::show()', $container);
    }
}
