<?php

namespace ContainerRSaQVVX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReponseControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator._e99RHe.App\Controller\ReponseController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator._e99RHe'] ?? $container->load('get_ServiceLocator_E99RHeService'));

        if (isset($container->privates['.service_locator._e99RHe.App\\Controller\\ReponseController::delete()'])) {
            return $container->privates['.service_locator._e99RHe.App\\Controller\\ReponseController::delete()'];
        }

        $instance = $a->withContext('App\\Controller\\ReponseController::delete()', $container);

        if (isset($container->privates['.service_locator._e99RHe.App\\Controller\\ReponseController::delete()'])) {
            return $container->privates['.service_locator._e99RHe.App\\Controller\\ReponseController::delete()'];
        }

        return $container->privates['.service_locator._e99RHe.App\\Controller\\ReponseController::delete()'] = $instance;
    }
}
