<?php

namespace ContainerRSaQVVX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getServiceProviderService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.1ITx0wW.App\Entity\ServiceProvider' shared service.
     *
     * @return \App\Entity\ServiceProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.1ITx0wW": it needs an instance of "App\\Entity\\ServiceProvider" but this type has been excluded because it\'s a Doctrine entity.');
    }
}
