<?php

namespace ContainerRSaQVVX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getServiceProviderControllerrecalculateScoreService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.h_GFj6c.App\Controller\Admin\ServiceProviderController::recalculateScore()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'provider' => ['privates', '.errored..service_locator.h_GFj6c.App\\Entity\\ServiceProvider', NULL, 'Cannot autowire service ".service_locator.h_GFj6c": it needs an instance of "App\\Entity\\ServiceProvider" but this type has been excluded because it\'s a Doctrine entity.'],
            'scoringService' => ['privates', 'App\\Service\\ProviderScoringService', 'getProviderScoringServiceService', true],
        ], [
            'provider' => 'App\\Entity\\ServiceProvider',
            'scoringService' => 'App\\Service\\ProviderScoringService',
        ]))->withContext('App\\Controller\\Admin\\ServiceProviderController::recalculateScore()', $container);

        if (isset($container->privates['.service_locator.h_GFj6c.App\\Controller\\Admin\\ServiceProviderController::recalculateScore()'])) {
            return $container->privates['.service_locator.h_GFj6c.App\\Controller\\Admin\\ServiceProviderController::recalculateScore()'];
        }

        return $container->privates['.service_locator.h_GFj6c.App\\Controller\\Admin\\ServiceProviderController::recalculateScore()'] = $instance;
    }
}
