<?php

namespace ContainerRSaQVVX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSchebTwoFactor_Security_Listener_CheckTwoFactorCodeReuseService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'scheb_two_factor.security.listener.check_two_factor_code_reuse' shared service.
     *
     * @return \Scheb\TwoFactorBundle\Security\Http\EventListener\CheckTwoFactorCodeReuseListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'scheb'.\DIRECTORY_SEPARATOR.'2fa-bundle'.\DIRECTORY_SEPARATOR.'Security'.\DIRECTORY_SEPARATOR.'Http'.\DIRECTORY_SEPARATOR.'EventListener'.\DIRECTORY_SEPARATOR.'CheckTwoFactorCodeReuseListener.php';

        $a = ($container->services['event_dispatcher'] ?? self::getEventDispatcherService($container));

        if (isset($container->privates['scheb_two_factor.security.listener.check_two_factor_code_reuse'])) {
            return $container->privates['scheb_two_factor.security.listener.check_two_factor_code_reuse'];
        }

        $instance = new \Scheb\TwoFactorBundle\Security\Http\EventListener\CheckTwoFactorCodeReuseListener($a, NULL, 60, ($container->privates['monolog.logger'] ?? self::getMonolog_LoggerService($container)));

        if (isset($container->privates['scheb_two_factor.security.listener.check_two_factor_code_reuse'])) {
            return $container->privates['scheb_two_factor.security.listener.check_two_factor_code_reuse'];
        }

        return $container->privates['scheb_two_factor.security.listener.check_two_factor_code_reuse'] = $instance;
    }
}
