<?php

namespace ContainerJoORxsq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_90BlalFService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.90BlalF' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'reclamation' => ['privates', '.errored..service_locator.90BlalF.App\\Entity\\Reclamation', NULL, 'Cannot autowire service ".service_locator.90BlalF": it needs an instance of "App\\Entity\\Reclamation" but this type has been excluded because it\'s a Doctrine entity.'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'reclamation' => 'App\\Entity\\Reclamation',
            'entityManager' => '?',
        ]);

        if (isset($container->privates['.service_locator.90BlalF'])) {
            return $container->privates['.service_locator.90BlalF'];
        }

        return $container->privates['.service_locator.90BlalF'] = $instance;
    }
}
