<?php

namespace ContainerJoORxsq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_E99RHeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator._e99RHe' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'reponse' => ['privates', '.errored..service_locator._e99RHe.App\\Entity\\Reponse', NULL, 'Cannot autowire service ".service_locator._e99RHe": it needs an instance of "App\\Entity\\Reponse" but this type has been excluded because it\'s a Doctrine entity.'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'reponse' => 'App\\Entity\\Reponse',
            'em' => '?',
        ]);

        if (isset($container->privates['.service_locator._e99RHe'])) {
            return $container->privates['.service_locator._e99RHe'];
        }

        return $container->privates['.service_locator._e99RHe'] = $instance;
    }
}
