<?php

namespace ContainerJoORxsq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEventControllerpublishService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.7jSP4cP.App\Controller\EventController::publish()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.7jSP4cP.App\\Controller\\EventController::publish()'] = ($container->privates['.service_locator.7jSP4cP'] ?? $container->load('get_ServiceLocator_7jSP4cPService'))->withContext('App\\Controller\\EventController::publish()', $container);
    }
}
