<?php

namespace ContainerJoORxsq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEmailVerificationControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\EmailVerificationController' shared autowired service.
     *
     * @return \App\Controller\EmailVerificationController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/EmailVerificationController.php';

        $container->services['App\\Controller\\EmailVerificationController'] = $instance = new \App\Controller\EmailVerificationController(($container->privates['App\\Repository\\UserRepository'] ?? $container->load('getUserRepositoryService')), ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->privates['mailer.mailer'] ?? $container->load('getMailer_MailerService')));

        $instance->setContainer(($container->privates['.service_locator.TJNRSaV'] ?? $container->load('get_ServiceLocator_TJNRSaVService'))->withContext('App\\Controller\\EmailVerificationController', $container));

        return $instance;
    }
}
