<?php

namespace ContainerJoORxsq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMailerDsnEnvVarProcessorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\DependencyInjection\MailerDsnEnvVarProcessor' shared autowired service.
     *
     * @return \App\DependencyInjection\MailerDsnEnvVarProcessor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/dependency-injection/EnvVarProcessorInterface.php';
        include_once \dirname(__DIR__, 4).'/src/DependencyInjection/MailerDsnEnvVarProcessor.php';

        return $container->privates['App\\DependencyInjection\\MailerDsnEnvVarProcessor'] = new \App\DependencyInjection\MailerDsnEnvVarProcessor();
    }
}
