<?php

namespace ContainerJoORxsq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMissionAwardedSubscriberService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\EventSubscriber\MissionAwardedSubscriber' shared autowired service.
     *
     * @return \App\EventSubscriber\MissionAwardedSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/EventSubscriber/MissionAwardedSubscriber.php';

        $a = ($container->privates['App\\Service\\ProviderScoringService'] ?? $container->load('getProviderScoringServiceService'));

        if (isset($container->privates['App\\EventSubscriber\\MissionAwardedSubscriber'])) {
            return $container->privates['App\\EventSubscriber\\MissionAwardedSubscriber'];
        }

        $instance = new \App\EventSubscriber\MissionAwardedSubscriber($a);

        if (isset($container->privates['App\\EventSubscriber\\MissionAwardedSubscriber'])) {
            return $container->privates['App\\EventSubscriber\\MissionAwardedSubscriber'];
        }

        return $container->privates['App\\EventSubscriber\\MissionAwardedSubscriber'] = $instance;
    }
}
