<?php

namespace ContainerJoORxsq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOrderServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\OrderService' shared autowired service.
     *
     * @return \App\Service\OrderService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/OrderService.php';

        return $container->privates['App\\Service\\OrderService'] = new \App\Service\OrderService(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->privates['App\\Service\\TicketQrCodeGenerator'] ?? $container->load('getTicketQrCodeGeneratorService')));
    }
}
