<?php

namespace ContainerJoORxsq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOrderControllerupdateStatusService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.2QpohGd.App\Controller\OrderController::updateStatus()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.2QpohGd.App\\Controller\\OrderController::updateStatus()'] = ($container->privates['.service_locator.2QpohGd'] ?? $container->load('get_ServiceLocator_2QpohGdService'))->withContext('App\\Controller\\OrderController::updateStatus()', $container);
    }
}
