<?php

namespace ContainerJoORxsq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProviderDashboardControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.1ITx0wW.App\Controller\ProviderDashboardController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.1ITx0wW.App\\Controller\\ProviderDashboardController::index()'] = ($container->privates['.service_locator.1ITx0wW'] ?? $container->load('get_ServiceLocator_1ITx0wWService'))->withContext('App\\Controller\\ProviderDashboardController::index()', $container);
    }
}
