<?php

namespace ContainerJoORxsq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProviderDashboardControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\ProviderDashboardController' shared autowired service.
     *
     * @return \App\Controller\ProviderDashboardController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/ProviderDashboardController.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/ux-chartjs/src/Builder/ChartBuilderInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/ux-chartjs/src/Builder/ChartBuilder.php';

        $container->services['App\\Controller\\ProviderDashboardController'] = $instance = new \App\Controller\ProviderDashboardController(($container->privates['App\\Repository\\ServiceBookingRepository'] ?? $container->load('getServiceBookingRepositoryService')), ($container->privates['App\\Repository\\ProviderScoreHistoryRepository'] ?? $container->load('getProviderScoreHistoryRepositoryService')), ($container->privates['App\\Repository\\ServiceProposalRepository'] ?? $container->load('getServiceProposalRepositoryService')), new \Symfony\UX\Chartjs\Builder\ChartBuilder());

        $instance->setContainer(($container->privates['.service_locator.TJNRSaV'] ?? $container->load('get_ServiceLocator_TJNRSaVService'))->withContext('App\\Controller\\ProviderDashboardController', $container));

        return $instance;
    }
}
