<?php

namespace ContainerJoORxsq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPappersVerificationServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\PappersVerificationService' shared autowired service.
     *
     * @return \App\Service\PappersVerificationService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/PappersVerificationService.php';

        return $container->privates['App\\Service\\PappersVerificationService'] = new \App\Service\PappersVerificationService(($container->privates['http_client.uri_template'] ?? self::getHttpClient_UriTemplateService($container)), $container->getEnv('INSEE_API_KEY'));
    }
}
