<?php

namespace ContainerJoORxsq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReponseControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.9iNU3ga.App\Controller\ReponseController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.9iNU3ga.App\\Controller\\ReponseController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'reponse' => ['privates', '.errored..service_locator.9iNU3ga.App\\Entity\\Reponse', NULL, 'Cannot autowire service ".service_locator.9iNU3ga": it needs an instance of "App\\Entity\\Reponse" but this type has been excluded because it\'s a Doctrine entity.'],
        ], [
            'reponse' => 'App\\Entity\\Reponse',
        ]))->withContext('App\\Controller\\ReponseController::show()', $container);
    }
}
