<?php

namespace ContainerJoORxsq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReglementControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\ReglementController' shared autowired service.
     *
     * @return \App\Controller\ReglementController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/ReglementController.php';

        $container->services['App\\Controller\\ReglementController'] = $instance = new \App\Controller\ReglementController();

        $instance->setContainer(($container->privates['.service_locator.TJNRSaV'] ?? $container->load('get_ServiceLocator_TJNRSaVService'))->withContext('App\\Controller\\ReglementController', $container));

        return $instance;
    }
}
