<?php

namespace ContainerJoORxsq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReclamationControllerbackOfficeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Qtf40Tq.App\Controller\ReclamationController::backOffice()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'reclamationRepository' => ['privates', 'App\\Repository\\ReclamationRepository', 'getReclamationRepositoryService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'reclamationRepository' => 'App\\Repository\\ReclamationRepository',
            'em' => '?',
        ]))->withContext('App\\Controller\\ReclamationController::backOffice()', $container);

        if (isset($container->privates['.service_locator.Qtf40Tq.App\\Controller\\ReclamationController::backOffice()'])) {
            return $container->privates['.service_locator.Qtf40Tq.App\\Controller\\ReclamationController::backOffice()'];
        }

        return $container->privates['.service_locator.Qtf40Tq.App\\Controller\\ReclamationController::backOffice()'] = $instance;
    }
}
