<?php

namespace ContainerJoORxsq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSponsorshipPackageTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\SponsorshipPackageType' shared autowired service.
     *
     * @return \App\Form\SponsorshipPackageType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/SponsorshipPackageType.php';

        return $container->privates['App\\Form\\SponsorshipPackageType'] = new \App\Form\SponsorshipPackageType();
    }
}
