<?php

namespace ContainerJoORxsq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getServiceRequestControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\ServiceRequestController' shared autowired service.
     *
     * @return \App\Controller\ServiceRequestController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/ServiceRequestController.php';

        $container->services['App\\Controller\\ServiceRequestController'] = $instance = new \App\Controller\ServiceRequestController(($container->privates['App\\Repository\\EventRepository'] ?? $container->load('getEventRepositoryService')), ($container->privates['App\\Repository\\ServiceRequestRepository'] ?? $container->load('getServiceRequestRepositoryService')), ($container->privates['App\\Repository\\ServiceProposalRepository'] ?? $container->load('getServiceProposalRepositoryService')), ($container->privates['App\\Repository\\ServiceProviderRepository'] ?? $container->load('getServiceProviderRepositoryService')), ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)));

        $instance->setContainer(($container->privates['.service_locator.TJNRSaV'] ?? $container->load('get_ServiceLocator_TJNRSaVService'))->withContext('App\\Controller\\ServiceRequestController', $container));

        return $instance;
    }
}
