<?php

namespace ContainerJoORxsq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getServiceBookingControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\ServiceBookingController' shared autowired service.
     *
     * @return \App\Controller\ServiceBookingController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/ServiceBookingController.php';

        $container->services['App\\Controller\\ServiceBookingController'] = $instance = new \App\Controller\ServiceBookingController(($container->privates['App\\Repository\\EventRepository'] ?? $container->load('getEventRepositoryService')), ($container->privates['App\\Repository\\ServiceBookingRepository'] ?? $container->load('getServiceBookingRepositoryService')), ($container->privates['App\\Repository\\ServiceProviderRepository'] ?? $container->load('getServiceProviderRepositoryService')), ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->privates['App\\Service\\ProviderScoringService'] ?? $container->load('getProviderScoringServiceService')));

        $instance->setContainer(($container->privates['.service_locator.TJNRSaV'] ?? $container->load('get_ServiceLocator_TJNRSaVService'))->withContext('App\\Controller\\ServiceBookingController', $container));

        return $instance;
    }
}
