<?php

namespace ContainerJoORxsq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSecurity_Authentication_KernelExceptionListener_TwoFactor_MainService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'security.authentication.kernel_exception_listener.two_factor.main' shared service.
     *
     * @return \Scheb\TwoFactorBundle\Security\Http\Firewall\ExceptionListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/scheb/2fa-bundle/Security/Http/Firewall/ExceptionListener.php';

        $a = ($container->services['event_dispatcher'] ?? self::getEventDispatcherService($container));

        if (isset($container->privates['security.authentication.kernel_exception_listener.two_factor.main'])) {
            return $container->privates['security.authentication.kernel_exception_listener.two_factor.main'];
        }

        $instance = new \Scheb\TwoFactorBundle\Security\Http\Firewall\ExceptionListener('main', ($container->privates['security.token_storage'] ?? self::getSecurity_TokenStorageService($container)), ($container->privates['security.authentication.authentication_required_handler.two_factor.main'] ?? $container->load('getSecurity_Authentication_AuthenticationRequiredHandler_TwoFactor_MainService')), $a);

        if (isset($container->privates['security.authentication.kernel_exception_listener.two_factor.main'])) {
            return $container->privates['security.authentication.kernel_exception_listener.two_factor.main'];
        }

        return $container->privates['security.authentication.kernel_exception_listener.two_factor.main'] = $instance;
    }
}
