<?php

namespace ContainerJoORxsq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getServiceRequestControllerawardService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator._PuVEKs.App\Controller\ServiceRequestController::award()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'serviceRequestStateMachine' => ['privates', 'debug.state_machine.service_request', 'getDebug_StateMachine_ServiceRequestService', false],
            'mailerService' => ['privates', 'App\\Service\\RfqMailerService', 'getRfqMailerServiceService', true],
            'dispatcher' => ['services', 'event_dispatcher', 'getEventDispatcherService', false],
        ], [
            'serviceRequestStateMachine' => '?',
            'mailerService' => 'App\\Service\\RfqMailerService',
            'dispatcher' => '?',
        ]))->withContext('App\\Controller\\ServiceRequestController::award()', $container);

        if (isset($container->privates['.service_locator._PuVEKs.App\\Controller\\ServiceRequestController::award()'])) {
            return $container->privates['.service_locator._PuVEKs.App\\Controller\\ServiceRequestController::award()'];
        }

        return $container->privates['.service_locator._PuVEKs.App\\Controller\\ServiceRequestController::award()'] = $instance;
    }
}
