<?php

namespace ContainerJoORxsq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getServiceRequestTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\ServiceRequestType' shared autowired service.
     *
     * @return \App\Form\ServiceRequestType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/ServiceRequestType.php';

        return $container->privates['App\\Form\\ServiceRequestType'] = new \App\Form\ServiceRequestType();
    }
}
