<?php

namespace ContainerJoORxsq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSecurity_Authenticator_TwoFactor_MainService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'security.authenticator.two_factor.main' shared service.
     *
     * @return \Scheb\TwoFactorBundle\Security\Http\Authenticator\TwoFactorAuthenticator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-http/Authenticator/AuthenticatorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-http/Authenticator/InteractiveAuthenticatorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/scheb/2fa-bundle/Security/Http/Authenticator/TwoFactorAuthenticator.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-http/Authentication/AuthenticationSuccessHandlerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-http/Util/TargetPathTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/scheb/2fa-bundle/Security/Http/Authentication/DefaultAuthenticationSuccessHandler.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-http/Authentication/AuthenticationFailureHandlerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/scheb/2fa-bundle/Security/Http/Authentication/DefaultAuthenticationFailureHandler.php';

        $a = ($container->services['event_dispatcher'] ?? self::getEventDispatcherService($container));

        if (isset($container->privates['security.authenticator.two_factor.main'])) {
            return $container->privates['security.authenticator.two_factor.main'];
        }
        $b = ($container->privates['security.firewall_config.two_factor.main'] ?? self::getSecurity_FirewallConfig_TwoFactor_MainService($container));
        $c = ($container->privates['security.http_utils'] ?? self::getSecurity_HttpUtilsService($container));

        $instance = new \Scheb\TwoFactorBundle\Security\Http\Authenticator\TwoFactorAuthenticator($b, ($container->privates['security.token_storage'] ?? self::getSecurity_TokenStorageService($container)), new \Scheb\TwoFactorBundle\Security\Http\Authentication\DefaultAuthenticationSuccessHandler($c, $b), new \Scheb\TwoFactorBundle\Security\Http\Authentication\DefaultAuthenticationFailureHandler($c, $b), ($container->privates['security.authentication.authentication_required_handler.two_factor.main'] ?? $container->load('getSecurity_Authentication_AuthenticationRequiredHandler_TwoFactor_MainService')), $a, ($container->privates['monolog.logger.security'] ?? self::getMonolog_Logger_SecurityService($container)));

        if (isset($container->privates['security.authenticator.two_factor.main'])) {
            return $container->privates['security.authenticator.two_factor.main'];
        }

        return $container->privates['security.authenticator.two_factor.main'] = $instance;
    }
}
