<?php

namespace ContainerJoORxsq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getServiceProviderControllerverifySiretService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.lfaqCvl.App\Controller\Admin\ServiceProviderController::verifySiret()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.lfaqCvl.App\\Controller\\Admin\\ServiceProviderController::verifySiret()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'pappersService' => ['privates', 'App\\Service\\PappersVerificationService', 'getPappersVerificationServiceService', true],
        ], [
            'pappersService' => 'App\\Service\\PappersVerificationService',
        ]))->withContext('App\\Controller\\Admin\\ServiceProviderController::verifySiret()', $container);
    }
}
