<?php

namespace ContainerJoORxsq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSchebTwoFactor_Security_TotpAuthenticatorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'scheb_two_factor.security.totp_authenticator' shared service.
     *
     * @return \Scheb\TwoFactorBundle\Security\TwoFactor\Provider\Totp\TotpAuthenticator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/scheb/2fa-totp/Security/TwoFactor/Provider/Totp/TotpAuthenticatorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/scheb/2fa-totp/Security/TwoFactor/Provider/Totp/TotpAuthenticator.php';

        $a = ($container->services['event_dispatcher'] ?? self::getEventDispatcherService($container));

        if (isset($container->services['scheb_two_factor.security.totp_authenticator'])) {
            return $container->services['scheb_two_factor.security.totp_authenticator'];
        }

        $instance = new \Scheb\TwoFactorBundle\Security\TwoFactor\Provider\Totp\TotpAuthenticator(($container->services['scheb_two_factor.security.totp_factory'] ?? $container->load('getSchebTwoFactor_Security_TotpFactoryService')), $a, 1);

        if (isset($container->services['scheb_two_factor.security.totp_authenticator'])) {
            return $container->services['scheb_two_factor.security.totp_authenticator'];
        }

        return $container->services['scheb_two_factor.security.totp_authenticator'] = $instance;
    }
}
