<?php

namespace ContainerJoORxsq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getServiceProvider2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.h_GFj6c.App\Entity\ServiceProvider' shared service.
     *
     * @return \App\Entity\ServiceProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.h_GFj6c": it needs an instance of "App\\Entity\\ServiceProvider" but this type has been excluded because it\'s a Doctrine entity.');
    }
}
