<?php

namespace ContainerJoORxsq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getServiceProposalControllercreateService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.H.h0zHf.App\Controller\ServiceProposalController::create()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.H.h0zHf'] ?? $container->load('get_ServiceLocator_H_H0zHfService'));

        if (isset($container->privates['.service_locator.H.h0zHf.App\\Controller\\ServiceProposalController::create()'])) {
            return $container->privates['.service_locator.H.h0zHf.App\\Controller\\ServiceProposalController::create()'];
        }

        $instance = $a->withContext('App\\Controller\\ServiceProposalController::create()', $container);

        if (isset($container->privates['.service_locator.H.h0zHf.App\\Controller\\ServiceProposalController::create()'])) {
            return $container->privates['.service_locator.H.h0zHf.App\\Controller\\ServiceProposalController::create()'];
        }

        return $container->privates['.service_locator.H.h0zHf.App\\Controller\\ServiceProposalController::create()'] = $instance;
    }
}
