<?php

namespace ContainerJoORxsq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTestMailerCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\TestMailerCommand' shared autowired service.
     *
     * @return \App\Command\TestMailerCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/TestMailerCommand.php';

        $container->privates['App\\Command\\TestMailerCommand'] = $instance = new \App\Command\TestMailerCommand(($container->privates['mailer.mailer'] ?? $container->load('getMailer_MailerService')), $container->getEnv('default::MAILER_FROM'));

        $instance->setName('app:mailer:test');
        $instance->setDescription('Send a test email to verify Gmail SMTP configuration');

        return $instance;
    }
}
