<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRSaQVVX\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRSaQVVX/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRSaQVVX.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRSaQVVX\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerRSaQVVX\App_KernelDevDebugContainer([
    'container.build_hash' => 'RSaQVVX',
    'container.build_id' => '397264a2',
    'container.build_time' => 1772588307,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRSaQVVX');
